# Generated by Django 3.2.7 on 2021-10-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_auto_20210927_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='MaxquantQc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='PDQc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='SpectromineQc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='TempData',
            field=models.BooleanField(default=False),
        ),
    ]
