# Generated by Django 3.2.7 on 2021-10-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_auto_20211004_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='MSGFQc',
            field=models.BooleanField(default=False),
        ),
    ]
