# Generated by Django 3.2.7 on 2021-10-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0006_alter_rawfile_rawfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='rawfile',
            field=models.FileField(null=True, upload_to='rawfiles/2021/10'),
        ),
    ]
