# Generated by Django 3.2.7 on 2021-10-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0007_alter_rawfile_rawfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='LastQC_PeptideID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='LastQC_ProteinID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='LastQC_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='LastQC_tool',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
