# Generated by Django 3.2.7 on 2021-10-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_auto_20211004_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='MSGFQc',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='MaxquantQc',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='PDQc',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='SpectromineQc',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='TempData',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
