# Generated by Django 3.2.7 on 2021-10-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0010_spectrominequeue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectromineWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workername', models.TextField(blank=True, max_length=100, null=True)),
                ('workerip', models.TextField(blank=True, max_length=100, null=True)),
                ('workerstatus', models.TextField(blank=True, max_length=100, null=True)),
                ('currentpercentage', models.IntegerField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('currentjob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.spectrominequeue')),
            ],
        ),
    ]
