# Generated by Django 3.2.7 on 2021-10-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0011_spectromineworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrominequeue',
            name='resultfile',
            field=models.FileField(blank=True, null=True, upload_to='results/2021/10'),
        ),
    ]
