# Generated by Django 3.2.7 on 2021-10-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0012_alter_spectrominequeue_resultfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='rawfile',
            field=models.FileField(null=True, upload_to='rawfiles/2021/10/10'),
        ),
    ]
