# Generated by Django 3.2.7 on 2021-10-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0014_alter_spectrominequeue_resultfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawfile',
            name='creator',
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='rawfile',
            field=models.FileField(null=True, upload_to='rawfiles/2021/10/11'),
        ),
        migrations.AlterField(
            model_name='spectrominequeue',
            name='resultfile',
            field=models.FileField(blank=True, null=True, upload_to='results/2021/10/11'),
        ),
    ]
