# Generated by Django 3.2.7 on 2021-10-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0019_auto_20211012_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to='notefiles/2021/10/12'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='rawfile',
            field=models.FileField(blank=True, null=True, upload_to='rawfiles/2021/10/12'),
        ),
    ]
