# Generated by Django 3.2.7 on 2021-10-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0022_spectrominequeue_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='notefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notefile', models.FileField(blank=True, null=True, upload_to='notefiles/2021/10/12')),
            ],
        ),
        migrations.RemoveField(
            model_name='rawfile',
            name='notefile',
        ),
    ]
