# Generated by Django 3.2.7 on 2021-10-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0023_auto_20211012_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='notefile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.notefile'),
        ),
    ]
