# Generated by Django 3.2.7 on 2021-10-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0024_rawfile_notefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawfile',
            name='notefile',
        ),
        migrations.AddField(
            model_name='rawfile',
            name='notefile',
            field=models.ManyToManyField(to='file_manager.NoteFile'),
        ),
    ]
