# Generated by Django 3.2.7 on 2021-10-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0025_auto_20211012_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='notefile',
            field=models.ManyToManyField(blank=True, null=True, to='file_manager.NoteFile'),
        ),
    ]
