# Generated by Django 3.2.7 on 2021-10-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0027_alter_rawfile_notefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notefile',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to='notefiles/2021/10/13'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='notefile',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='rawfile',
            field=models.FileField(blank=True, null=True, upload_to='rawfiles/2021/10/13'),
        ),
        migrations.AlterField(
            model_name='spectrominequeue',
            name='resultfile',
            field=models.FileField(blank=True, null=True, upload_to='results/2021/10/13'),
        ),
    ]
