# Generated by Django 3.2.7 on 2021-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0028_auto_20211013_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='acquired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='notefile',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
