# Generated by Django 3.2.7 on 2021-10-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0029_auto_20211013_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawfile',
            old_name='acquired_at',
            new_name='acquisitiontime',
        ),
        migrations.AddField(
            model_name='rawfile',
            name='instrumentmodel',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='instrumentsn',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='sampletype',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='notefile',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
