# Generated by Django 3.2.7 on 2021-10-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0030_auto_20211013_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notefile',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to='notefiles/2021/10/14'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='notefile',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='rawfile',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='spectrominequeue',
            name='resultfile',
            field=models.FileField(blank=True, null=True, upload_to='results/2021/10/14'),
        ),
    ]
