# Generated by Django 3.2.7 on 2021-10-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0031_auto_20211014_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='notefile',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
