# Generated by Django 3.2.7 on 2021-10-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0035_auto_20211015_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='notefile',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
