# Generated by Django 3.2.7 on 2021-10-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0036_alter_rawfile_notefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='pklfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notefile',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to='notefiles/2021/10/18'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='notefile',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
        migrations.AlterField(
            model_name='spectrominequeue',
            name='resultfile',
            field=models.FileField(blank=True, null=True, upload_to='results/2021/10/18'),
        ),
    ]
