# Generated by Django 3.2.7 on 2021-10-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0037_auto_20211018_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='HdStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filelocation', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filelocation', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filelocation', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SsdStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filelocation', models.FileField(blank=True, null=True, upload_to='temp/')),
            ],
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='acquisitiontime',
            new_name='acquisition_time',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='instrumentmodel',
            new_name='instrument_model',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='instrumentsn',
            new_name='instrument_sn',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='LastQC_PeptideID',
            new_name='lastqc_peptide_id',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='LastQC_ProteinID',
            new_name='lastqc_protein_id',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='LastQC_time',
            new_name='lastqc_time',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='LastQC_tool',
            new_name='lastqc_tool',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='MaxquantQc',
            new_name='maxquant_qc',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='MSGFQc',
            new_name='msgfq_qc',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='notefile',
            new_name='note_file',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='PDQc',
            new_name='pd_qc',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='desc',
            new_name='run_desc',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='name',
            new_name='run_name',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='sampletype',
            new_name='sample_type',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='SpectromineQc',
            new_name='spectromine_qc',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='TempData',
            new_name='temp_data',
        ),
        migrations.RenameField(
            model_name='spectrominequeue',
            old_name='finishedtime',
            new_name='finished_time',
        ),
        migrations.RenameField(
            model_name='spectrominequeue',
            old_name='PeptideID',
            new_name='peptide_id',
        ),
        migrations.RenameField(
            model_name='spectrominequeue',
            old_name='ProteinID',
            new_name='protein_id',
        ),
        migrations.RenameField(
            model_name='spectrominequeue',
            old_name='Rawfile',
            new_name='rawfile',
        ),
        migrations.RenameField(
            model_name='spectrominequeue',
            old_name='runstatus',
            new_name='run_status',
        ),
        migrations.RenameField(
            model_name='spectrominequeue',
            old_name='starttime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='spectromineworker',
            old_name='currentjob',
            new_name='current_job',
        ),
        migrations.RenameField(
            model_name='spectromineworker',
            old_name='currentpercentage',
            new_name='current_percentage',
        ),
        migrations.RenameField(
            model_name='spectromineworker',
            old_name='lastupdate',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='spectromineworker',
            old_name='workerip',
            new_name='worker_ip',
        ),
        migrations.RenameField(
            model_name='spectromineworker',
            old_name='workername',
            new_name='worker_name',
        ),
        migrations.RenameField(
            model_name='spectromineworker',
            old_name='workerstatus',
            new_name='worker_status',
        ),
        migrations.RemoveField(
            model_name='spectrominequeue',
            name='resultfile',
        ),
        migrations.AddField(
            model_name='spectrominequeue',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='results/2021/10/            21'),
        ),
        migrations.AlterField(
            model_name='notefile',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to='notefiles/2021/         10/21'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='hd_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.hdstorage'),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='offline_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.offlinestorage'),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='remote_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.remotestorage'),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='ssd_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.ssdstorage'),
        ),
    ]
