# Generated by Django 3.2.7 on 2021-10-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('file_manager', '0038_auto_20211021_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='object_id',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
