# Generated by Django 3.2.7 on 2021-10-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0039_auto_20211021_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='content_extracted',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='notefile',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to='notefiles/2021/         10/22'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
        migrations.AlterField(
            model_name='spectrominequeue',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='results/2021/10/            22'),
        ),
    ]
