# Generated by Django 3.2.7 on 2021-11-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0044_auto_20211105_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='plot_label',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
