# Generated by Django 3.2.7 on 2021-11-06 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_manager', '0045_auto_20211105_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxquantQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.TextField(blank=True, max_length=100, null=True)),
                ('setting_xml', models.FileField(blank=True, null=True, upload_to='maxquant_xml/2021/11/            6')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='results/2021/11/            6')),
                ('protein_file', models.FileField(blank=True, null=True, upload_to='results/2021/11/            6')),
                ('peptide_file', models.FileField(blank=True, null=True, upload_to='results/2021/11/            6')),
                ('other_file', models.FileField(blank=True, null=True, upload_to='results/2021/11/            6')),
                ('run_status', models.BooleanField(default=False, null=True)),
                ('protein_id', models.IntegerField(blank=True, null=True)),
                ('peptide_id', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notefile',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to='notefiles/2021/         11/6'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
        migrations.AlterField(
            model_name='spectrominequeue',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='results/2021/11/            6'),
        ),
        migrations.CreateModel(
            name='MaxquantWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.TextField(blank=True, max_length=100, null=True)),
                ('worker_ip', models.TextField(blank=True, max_length=100, null=True)),
                ('worker_status', models.TextField(blank=True, max_length=100, null=True)),
                ('current_percentage', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.maxquantqueue')),
            ],
        ),
        migrations.AddField(
            model_name='maxquantqueue',
            name='rawfile',
            field=models.ManyToManyField(blank=True, null=True, to='file_manager.RawFile'),
        ),
    ]
