# Generated by Django 3.2.7 on 2021-12-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('file_manager', '0050_auto_20211203_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='qc_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_content', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='qc_object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
