# Generated by Django 3.2.7 on 2021-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0051_auto_20211203_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxquantqueue',
            name='rawfile',
            field=models.ManyToManyField(to='file_manager.RawFile'),
        ),
        migrations.AlterField(
            model_name='msfraggerqueue',
            name='rawfile',
            field=models.ManyToManyField(to='file_manager.RawFile'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
