# Generated by Django 3.2.7 on 2021-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0052_auto_20211203_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawfile',
            name='lastqc_peptide_id',
        ),
        migrations.RemoveField(
            model_name='rawfile',
            name='lastqc_protein_id',
        ),
        migrations.RemoveField(
            model_name='rawfile',
            name='lastqc_time',
        ),
        migrations.RemoveField(
            model_name='rawfile',
            name='lastqc_tool',
        ),
        migrations.RemoveField(
            model_name='rawfile',
            name='maxquant_qc',
        ),
        migrations.RemoveField(
            model_name='rawfile',
            name='msgfq_qc',
        ),
        migrations.RemoveField(
            model_name='rawfile',
            name='pd_qc',
        ),
        migrations.RemoveField(
            model_name='rawfile',
            name='spectromine_qc',
        ),
        migrations.AddField(
            model_name='rawfile',
            name='qc_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
