# Generated by Django 3.2.7 on 2021-12-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0053_auto_20211203_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawfile',
            old_name='qc_type',
            new_name='qc_tool',
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
