# Generated by Django 3.2.7 on 2021-12-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0054_auto_20211203_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='qc_mbr',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
