# Generated by Django 3.2.7 on 2022-01-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0056_auto_20220114_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdqueue',
            name='precurosr_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
