# Generated by Django 3.2.7 on 2022-02-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0060_alter_rawfile_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='sample_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
