# Generated by Django 3.2.7 on 2022-02-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0063_auto_20220208_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='storage_option',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maxquantqueue',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/maxquant/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='maxquantqueue',
            name='other_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/maxquant/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='maxquantqueue',
            name='peptide_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/maxquant/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='maxquantqueue',
            name='protein_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/maxquant/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='maxquantqueue',
            name='setting_xml',
            field=models.FileField(blank=True, null=True, upload_to='maxquant_xml/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='msfraggerqueue',
            name='ion_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/msfragger/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='msfraggerqueue',
            name='peptide_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/msfragger/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='msfraggerqueue',
            name='protein_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/msfragger/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='msfraggerqueue',
            name='psm_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/msfragger/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='notefile',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to='notefiles/2022/         2/9'),
        ),
        migrations.AlterField(
            model_name='pdqueue',
            name='consensus_method',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='pdqueue',
            name='export_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='pdqueue',
            name='processing_method',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='pdqueue',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/9'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
        migrations.AlterField(
            model_name='spectrominequeue',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/spectromine/2022/2/9'),
        ),
    ]
