# Generated by Django 3.2.7 on 2022-02-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0065_auto_20220216_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdqueue',
            old_name='TMT',
            new_name='replace_qc',
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
