# Generated by Django 3.2.7 on 2022-02-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0067_alter_rawfile_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdqueue',
            name='replace_qc',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
