# Generated by Django 3.2.7 on 2022-02-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0068_auto_20220216_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdqueue',
            name='consensus_method',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/16/methods'),
        ),
        migrations.AlterField(
            model_name='pdqueue',
            name='processing_method',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/16/methods'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
    ]
