# Generated by Django 3.2.7 on 2022-02-28 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_manager', '0072_alter_rawfile_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxquantqueue',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/maxquant/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='maxquantqueue',
            name='other_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/maxquant/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='maxquantqueue',
            name='peptide_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/maxquant/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='maxquantqueue',
            name='protein_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/maxquant/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='maxquantqueue',
            name='setting_xml',
            field=models.FileField(blank=True, null=True, upload_to='maxquant_xml/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='msfraggerqueue',
            name='ion_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/msfragger/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='msfraggerqueue',
            name='peptide_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/msfragger/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='msfraggerqueue',
            name='protein_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/msfragger/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='msfraggerqueue',
            name='psm_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/msfragger/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='notefile',
            name='notefile',
            field=models.FileField(blank=True, null=True, upload_to='notefiles/2022/         2/28'),
        ),
        migrations.AlterField(
            model_name='pdqueue',
            name='consensus_method',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/28/methods'),
        ),
        migrations.AlterField(
            model_name='pdqueue',
            name='export_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='pdqueue',
            name='processing_method',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/28/methods'),
        ),
        migrations.AlterField(
            model_name='pdqueue',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/proteindiscoverer/2022/2/28'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='note_file',
            field=models.ManyToManyField(blank=True, to='file_manager.NoteFile'),
        ),
        migrations.AlterField(
            model_name='spectrominequeue',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='hdstorage/spectromine/2022/2/28'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_otherresult', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
