# Generated by Django 3.2.7 on 2022-10-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='system_backup_settings',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='appauthor',
            name='image_link',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/images/'),
        ),
        migrations.AlterField(
            model_name='dataanalysisqueue',
            name='input_file_1',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/dataqueue/uniquetempfolder'),
        ),
        migrations.AlterField(
            model_name='dataanalysisqueue',
            name='input_file_2',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/dataqueue/uniquetempfolder'),
        ),
        migrations.AlterField(
            model_name='dataanalysisqueue',
            name='input_file_3',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/dataqueue/uniquetempfolder'),
        ),
        migrations.AlterField(
            model_name='dataanalysisqueue',
            name='output_file_1',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/dataqueue/uniquetempfolder'),
        ),
        migrations.AlterField(
            model_name='dataanalysisqueue',
            name='output_file_2',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/dataqueue/uniquetempfolder'),
        ),
        migrations.AlterField(
            model_name='dataanalysisqueue',
            name='output_file_3',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/dataqueue/uniquetempfolder'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/images/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='install_package',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/codes/install'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_1',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_10',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_2',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_3',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_4',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_5',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_6',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_7',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_8',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='preset_9',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/presets/'),
        ),
        migrations.AlterField(
            model_name='processingapp',
            name='process_package',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/codes/processing'),
        ),
        migrations.AlterField(
            model_name='samplerecord',
            name='temp_rawfile',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/temp/'),
        ),
        migrations.AlterField(
            model_name='visualizationapp',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/images/'),
        ),
    ]
