# Generated by Django 3.2.15 on 2022-12-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationapp',
            name='install_package',
            field=models.FileField(blank=True, null=True, upload_to='primary_storage/systemfiles/codes/install'),
        ),
    ]
