# Generated by Django 3.2.7 on 2022-10-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_auto_20221024_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='system_backup_settings',
            new_name='systemfile_backup_settings',
        ),
    ]
