# Generated by Django 3.2.15 on 2022-12-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_visualizationapp_install_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizationapp',
            name='support_process_apps',
        ),
        migrations.AddField(
            model_name='visualizationapp',
            name='support_process_apps',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
