# Generated by Django 3.2.15 on 2022-12-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_auto_20221211_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingapp',
            old_name='lastest_version',
            new_name='downloaded_version',
        ),
        migrations.RenameField(
            model_name='processingapp',
            old_name='lastest_update',
            new_name='last_install',
        ),
        migrations.RenameField(
            model_name='visualizationapp',
            old_name='lastest_version',
            new_name='download_version',
        ),
        migrations.RenameField(
            model_name='visualizationapp',
            old_name='lastest_update',
            new_name='last_update',
        ),
    ]
