# Generated by Django 3.2.15 on 2022-12-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_auto_20221212_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualizationapp',
            old_name='download_version',
            new_name='downloaded_version',
        ),
    ]
