# Generated by Django 3.2.15 on 2022-12-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_rename_download_version_visualizationapp_downloaded_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingapp',
            name='last_install',
            field=models.DateTimeField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='visualizationapp',
            name='last_update',
            field=models.DateTimeField(default=False, null=True),
        ),
    ]
