# Generated by Django 3.2.15 on 2022-12-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0006_auto_20221212_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingapp',
            name='last_install',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualizationapp',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
