# Generated by Django 3.2.15 on 2022-12-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0007_auto_20221212_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualizationapp',
            old_name='last_update',
            new_name='last_install',
        ),
    ]
