version: '1'
services:
  web:
    environment:
      PYTHONUNBUFFERED: 1
    build: .
    volumes:
      - type: bind
        source: //d/docker/primary_storage #host folder in windows, means d:/docker/primary_raw
        target: //app/media//primary_storage
      - type: bind
        source: //d/docker/secondary_storage # means d:/docker/secondary_raw
        target: //app/media//secondary_storage
      - type: bind
        source: //d/docker/remote_storage #means d:/docker/remote
        target: //app/media//remote_storage
      - type: bind
        source: //d/docker/offline_storage #means d:/docker/offline
        target: //app/media//offline_storage

    command: /venv/bin/python3 manage.py runserver  0.0.0.0:8000
    ports:
      - 80:8000
  nginx:
    image: nginx:latest
    container_name: ng
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
    depends_on:
      - web
